server:
  host: "0.0.0.0"
  port: 5000

location:
  place: New_York_City
  building: New_York_University_hospital
  floor: "17th_floor"
  scale: 0.0215769999

IO_root: "/root/UNav-IO"

devices: "cuda:0"

hloc:
  retrieval_num: 100
  implicit_num: 1
  ransac_thre: 10
  # match_type: 'nvs'
  match_type: "lightglue"
  batch_mode: true
  load_all_maps: False
  map_loading_keyframes_reload: 0

feature:
  global:
    netvlad:
      ckpt_path: "parameters/paper"
      arch: "vgg16"
      vladv2: true
      nocuda: false
      num_clusters: 64
      pooling: "netvlad"

  local:
    superpoint+lightglue:
      detector_name: superpoint
      nms_radius: 4
      max_keypoints: 4096
      matcher_name: lightglue
      match_conf:
        width_confidence: -1
        depth_confidence: -1
